### ISSUE TITLE
Cached data not updated

### ISSUE THREAD

**Issue by booooohdan** [zeshuaro/firestore_cache#89]
Updated status timestamp, but the app does not use new data, only show old cached data.
Old date was: 12.03.2022
New date:
![image](https://user-images.githubusercontent.com/30977443/163625868-340c6d5b-48e8-4f9a-8e6b-8e17c7a49d1a.png)

There a cache logic:
```
Future<QuerySnapshot<Map<String, dynamic>>> getPlanesDocs() async {
    final cacheDocRef = _fireStoreInstance.doc('statusplane/status');
    const cacheField = 'updatedAt';
    final query = _fireStoreInstance.collection('planes');
    final snapshot = await FirestoreCache.getDocuments(
      query: query,
      cacheDocRef: cacheDocRef,
      firestoreCacheField: cacheField,
    );

    return snapshot;
  }

  Future<List<Vehicle>> getSimplifiedPlanes() async {
    final List<Vehicle> planesList = [];
    await getPlanesDocs().then((value) => value.docs.forEach((doc) {
          final plane = Vehicle(
            link: doc['link'],
            name: doc['name'],
            image: doc['image'],
            nation: doc['nation'],
            rank: doc['rank'],
            BRs: doc['BRs'].cast<String>(),
            isPremium: doc['isPremium'],
            vehicleClass: doc['planeClass'].cast<String>(),
          );

          planesList.add(plane);
        }));

    return planesList;
  }
```
Full code: https://github.com/booooohdan/flutter_wt_versus/blob/develop/lib/providers/firestore_provider.dart
What I'm doing wrong?

**Comment by zeshuaro** [comment]
Hey @booooohdan, thanks for raising this issue. Your code looks alright to me and if the timestamp field is updated on Firestore, it should be fetching from the server instead of the cache. 

I would suggest putting a breakpoint [here](https://github.com/zeshuaro/firestore_cache/blob/main/lib/src/firestore_cache.dart#L94) to debug and check the variable `isFetch`. This variable is returned by [this](https://github.com/zeshuaro/firestore_cache/blob/main/lib/src/firestore_cache.dart#L118-L155) function, which is used to determine whether we should fetch from server or cache. If the variable is set to:
- `true`: then it should be using the default Firestore behaviour, which is to fetch from server first and fallback to cache if there's no internet access. If this is the case, check if your device has internet access.
- `false`: then I'm interested in putting a breakpoint [here](https://github.com/zeshuaro/firestore_cache/blob/main/lib/src/firestore_cache.dart#L150) and see if the code ever reaches this line, where the function determined that it shouldn't be fetching from the server. I'm also interested to see the values of `cacheDate` and `serverDate`.

If you can try the above and share the extra information with me, then we can further investigate what the issue is.

**Comment by booooohdan** [comment]
I debug your lib (I wonder, that's pretty easy code)
All worked correctly, but I have this date as cacheDate (2022-04-16 17:15:14). I don't know how this data was set. This is a strange moment and a reason for the bug. I think you need check where date is stored in prefs (cachedDate), probably cacheDate rewrited somewhere

![image](https://user-images.githubusercontent.com/30977443/163685628-952b2f75-a81d-482a-921f-d0363afce712.png)

**Comment by zeshuaro** [comment]
Okay, so I think the issue here is that you have multiple different queries, but they're all being cached under the same key. The default behaviour is that it will use the `firestoreCacheField` as the local key. Since all your queries have the same `firestoreCacheField`, the local key will be the same for all your queries. And so the `cacheDate` gets overridden by each query.

I would suggest you to specify the `localCacheKey` argument for different queries to set a different cache key for different queries.
